name: sky
description: HDFC Sky CLI tool for flutter project.
version: 1.1.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.3.7
  args: ^2.4.1
  cli_completion: ^0.3.0
  git: ^2.2.1
  http: ^1.1.0
  mason_logger: ^0.2.8
  path: ^1.8.3
  pub_semver: ^2.1.4
  pub_updater: ^0.3.0
  scoped:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/scoped
  secure_dotenv: ^1.0.0
  system_info2: ^4.0.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^5.0.0

executables:
  sky:
